"""updating business models suport

Revision ID: 95512eef3028
Revises: 3c959842f1b6
Create Date: 2026-06-19 19:13:31.977528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95512eef3028'
down_revision: Union[str, Sequence[str], None] = '3c959842f1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_read_sessions',
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_seconds', sa.Integer(), nullable=False),
    sa.Column('max_scroll_percent', sa.Integer(), nullable=False),
    sa.Column('tab_visible', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_qualified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_read_sessions_content_id'), 'content_read_sessions', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_read_sessions_user_id'), 'content_read_sessions', ['user_id'], unique=False)
    op.add_column('contents', sa.Column('views_count', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_contents_author_id'), 'contents', ['author_id'], unique=False)
    op.create_index(op.f('ix_contents_category_id'), 'contents', ['category_id'], unique=False)
    op.create_index(op.f('ix_contents_content_type'), 'contents', ['content_type'], unique=False)
    op.create_index(op.f('ix_contents_hub_id'), 'contents', ['hub_id'], unique=False)
    op.create_index(op.f('ix_contents_is_premium'), 'contents', ['is_premium'], unique=False)
    op.create_index(op.f('ix_contents_status'), 'contents', ['status'], unique=False)
    op.create_index(op.f('ix_contents_views_count'), 'contents', ['views_count'], unique=False)
    op.create_index(op.f('ix_contents_visibility'), 'contents', ['visibility'], unique=False)
    op.create_index(op.f('ix_partnerships_plan'), 'partnerships', ['plan'], unique=False)
    op.create_index(op.f('ix_partnerships_referral_creator_id'), 'partnerships', ['referral_creator_id'], unique=False)
    op.create_index(op.f('ix_partnerships_status'), 'partnerships', ['status'], unique=False)
    op.create_index(op.f('ix_partnerships_user_id'), 'partnerships', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_partnerships_user_id'), table_name='partnerships')
    op.drop_index(op.f('ix_partnerships_status'), table_name='partnerships')
    op.drop_index(op.f('ix_partnerships_referral_creator_id'), table_name='partnerships')
    op.drop_index(op.f('ix_partnerships_plan'), table_name='partnerships')
    op.drop_index(op.f('ix_contents_visibility'), table_name='contents')
    op.drop_index(op.f('ix_contents_views_count'), table_name='contents')
    op.drop_index(op.f('ix_contents_status'), table_name='contents')
    op.drop_index(op.f('ix_contents_is_premium'), table_name='contents')
    op.drop_index(op.f('ix_contents_hub_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_content_type'), table_name='contents')
    op.drop_index(op.f('ix_contents_category_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_author_id'), table_name='contents')
    op.drop_column('contents', 'views_count')
    op.drop_index(op.f('ix_content_read_sessions_user_id'), table_name='content_read_sessions')
    op.drop_index(op.f('ix_content_read_sessions_content_id'), table_name='content_read_sessions')
    op.drop_table('content_read_sessions')
    # ### end Alembic commands ###
