"""partnership_payment model

Revision ID: be8d85389559
Revises: 95512eef3028
Create Date: 2026-06-29 21:32:42.785124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be8d85389559'
down_revision: Union[str, Sequence[str], None] = '95512eef3028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partnership_payments',
    sa.Column('partnership_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.Enum('MPESA', name='paymentprovider'), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'TIMEOUT', name='paymentstatus'), nullable=False),
    sa.Column('plan', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('merchant_request_id', sa.String(length=120), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=120), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(length=120), nullable=True),
    sa.Column('result_code', sa.String(length=20), nullable=True),
    sa.Column('result_desc', sa.Text(), nullable=True),
    sa.Column('raw_request', sa.JSON(), nullable=True),
    sa.Column('raw_callback', sa.JSON(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partnership_id'], ['partnerships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partnership_payments_checkout_request_id'), 'partnership_payments', ['checkout_request_id'], unique=False)
    op.create_index(op.f('ix_partnership_payments_partnership_id'), 'partnership_payments', ['partnership_id'], unique=False)
    op.create_index(op.f('ix_partnership_payments_status'), 'partnership_payments', ['status'], unique=False)
    op.create_index(op.f('ix_partnership_payments_user_id'), 'partnership_payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partnership_payments_user_id'), table_name='partnership_payments')
    op.drop_index(op.f('ix_partnership_payments_status'), table_name='partnership_payments')
    op.drop_index(op.f('ix_partnership_payments_partnership_id'), table_name='partnership_payments')
    op.drop_index(op.f('ix_partnership_payments_checkout_request_id'), table_name='partnership_payments')
    op.drop_table('partnership_payments')
    # ### end Alembic commands ###
