"""add education children relationships

Revision ID: e30fa7ca6b37
Revises: d91ec39caaad
Create Date: 2026-05-16 01:48:08.269438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30fa7ca6b37'
down_revision: Union[str, Sequence[str], None] = 'd91ec39caaad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_children_content_content', 'children_contents', ['content_id'])
    op.create_unique_constraint('uq_education_resource_content', 'education_resources', ['content_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_education_resource_content', 'education_resources', type_='unique')
    op.drop_constraint('uq_children_content_content', 'children_contents', type_='unique')
    # ### end Alembic commands ###
