"""add content assets table

Revision ID: ec56bafefa73
Revises: bf9cbeb8cc38
Create Date: 2026-06-11 20:43:53.679214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec56bafefa73'
down_revision: Union[str, Sequence[str], None] = 'bf9cbeb8cc38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_assets',
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.Enum('IMAGE', 'FILE', name='contentassettype'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_assets_content_id'), 'content_assets', ['content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_assets_content_id'), table_name='content_assets')
    op.drop_table('content_assets')
    # ### end Alembic commands ###
